[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry"]

[tool.poetry]
authors = ["Artem Malyshev <proofit404@gmail.com>"]
description = "Dependency Injection for Humans"
documentation = "https://proofit404.github.io/dependencies/"
homepage = "https://pypi.org/project/dependencies/"
license = "BSD-2-Clause"
name = "dependencies"
packages = [
    { include = "_dependencies", from = "src" },
    { include = "dependencies", from = "src" },
]
readme = "docs/index.md"
repository = "https://github.com/proofit404/dependencies/"
version = "5.0.0"

[tool.poetry.dependencies]
python = "~3.7 || ~3.8 || ~3.9"

[tool.poetry.urls]
Changelog = "https://proofit404.github.io/dependencies/"
Issues = "https://github.com/proofit404/dependencies/issues"
