---
name: pull request
"on":
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - run: |
          git checkout develop || true
          git checkout $GITHUB_HEAD_REF
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9.13
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - uses: actions/setup-python@v3
        with:
          python-version: pypy-3.9
      - run: rm /opt/hostedtoolcache/PyPy/3.9.12/x64/bin/python3.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: ./scripts/install
      - run: ./scripts/check
      - run: ./scripts/test
        env:
          TOX_SKIP_ENV: mutmut
      - run: ./scripts/review
        env:
          DANGER_GITHUB_API_TOKEN: Z2hwX3BZbXFOQWJXMkNkT0NwejNGS1BWZjBWZ3hTS01uSjJRSmVQbAo=
